# coding=utf-8
APP_MODE = 'development'

DB_HOST = 'localhost'
DB_PORT = 3306
DB_DATABASE = ''
DB_USERNAME = ''
DB_PASSWORD = ''
# 最大连接数
DB_MAX_CONNECTIONS = 4
# 连接超时
DB_STALE_TIMEOUT = 300

WELINK_SMS_API_SNAME = ''
WELINK_SMS_API_SPWD = ''
WELINK_SMS_API_SCORPID = None
WELINK_SMS_API_SPRDID = ''

WEIXIN_API_APPID = ''
WEIXIN_API_SECRET = ''
